var allSubject = {
"Sta114":[{"Question":"If x = [23, 21,32,40,45, 10] and y = [100, 94, 150, 160,180,80]. What would be the value of x if y = 200.",
"Option":{"a":"52.1236",
"b":"52.1243",
"c":"52.1234",
"d":"52.4321",
"e":"52.1324"},
"image":"",
"Answer":"e"},

{"Question":"If β = 0,",
"Option":{"a":"X and Y are linearly dependent",
"b":"X and Y are not linearly dependent",
"c":"X and Y are the same",
"d":"X and Y are inversely related",
"e":"X and Y are directly related"},
"image":"",
"Answer":"b"},

{"Question":"If x = [23, 21,32,40,45, 10] and y = [100,94,150,160,180, 80]. Obtain the linear model of the relationship between y and x.",
"Option":{"a":"y = 22.071 + 3.563x",
"b":"y = 39.693 + 3.563x",
"c":"y = 39.693 + 3.075x",
"d":"y = 22.071 + 3.075x",
"e":"y = 39.693 + 3.705x"},
"image":"",
"Answer":"c"},

{"Question":"If X and Y rise or fall together, then",
"Option":{
"a":"r = 0",
"b":"r <=1",
"c":"r < 0",
"d":"r > 0",
"e":"No answer"},
"image":"",
"Answer":"d"},

{"Question":"If x = [23,21,32,40,45] and y = [100,94,150,160,180]. Obtain the slope or parameter of the relationship between y and x.",
"Option":{
"a":"22.701",
"b":"3.653",
"c":"22.071",
"d":"3.563",
"e":"No answer"},
"image":"",
"Answer":"d"},

{"Question":"What is the correlation between X and Y if y = (100,94,150,160,180,80), and x = (23,21,32,40,45, 10).",
"Option":{
"a":"0.9275",
"b":"0.9257",
"c":"0.9752",
"d":"0.9725",
"e":"No answer"},
"image":"",
"Answer":"d"},

{"Question":" If x = [23,21,32,40,45, 10] and y = [100,94,150,160,180,80]. What would be the value of y if x = 20.",
"Option":{
"a":"101.913",
"b":"101.139",
"c":"101.319",
"d":"101.193",
"e":"101.391"},
"image":"",
"Answer":"d"},

{"Question":" If x = [23,21,32,40,45] and y = [100,94,150,160,180]. Obtain the intercept of the relationship between y and x.",
"Option":{
"a":"3.563",
"b":"22.701",
"c":"3.653",
"d":"22.071",
"e":"No answer"},
"image":"",
"Answer":"d"},

{"Question":"If Y and X are inversely related, then",
"Option":{"a":"β <= 0",
"b":"β > 0",
"c":"β = 0",
"d":"β < 0",
"e":"No answer"},
"image":"",
"Answer":"d"},

{"Question":"What is the correlation between X and Y if y = (100,94,150,160,180), and x = (23,21,32,40,45).",
"Option":{
"a":"0.9758",
"b":"0.9785",
"c":"0.9578",
"d":"0.9587",
"e":"No answer"},
"image":"",
"Answer":"d"},

{"Question":"Boxplot presents the following except?",
"Option":{"a":"presence of outliers",
"b":"quartiles",
"c":"spreads",
"d":"five nums",
"e":"partitions"},
"image":"",
"Answer":"c"},

{"Question":"Given the following frequencies; 2, 3, 5, 16, 3, 5. What is the cumulative frequency of the fourth class?",
"Option":{
"a":"34",
"b":"16",
"c":"10",
"d":"26",
"e":"29"},
"image":"",
"Answer":"d"},

{"Question":"Given the following class interval; [20 - 25], [25 -30], [30-35], . . . , [45 - 50]. What is the sum of the class width?",
"Option":{"a":"30",
"b":"40",
"c":"36",
"d":"35",
"e":"24"},
"image":"",
"Answer":"a"},

{"Question":"To construct histogram, which of the following is necessary?",
"Option":{"a":"Class interval",
"b":"Class width",
"c":"Class boundary",
"d":"Class frequency",
"e":"Class midpoint"},
"image":"",
"Answer":"c"},

{"Question":"Which year records the least population of wildlife? ",
"Option":{"a":"2017",
"b":"2018",
"c":"2019",
"d":"2020",
"e":"2021"},
"image":"",
"Answer":"c"},


{"Question":"Given the following class interval; [20 - 24], [25 -29], [30-34]. . . The class width is?",
"Option":{
"a":"4",
"b":"3",
"c":"5",
"d":"4.5",
"e":"None of the above"},
"image":"",
"Answer":"c"},


{"Question":"What is the critical value if n = 100 and confidence interval is 99%?",
"Option":{
"a":"1.96",
"b":"2.32",
"c":"2.63",
"d":"1.68",
"e":"2.58"},
"image":"",
"Answer":"e"},

{"Question":"Out 1500 students in Idia hostel, 1000 are allergic to Zikites so often avoid Zik hall route. Half of the remaining proportion wouldn't use Indy route as well. Obtain 95% confidence interval of the true population proportion of students who would use Zik route?",
"Option":{
"a":"[0.6353, 0.6981]",
"b":"[0.3019, 0.3647]",
"c":"[0.8145, 0.8522]",
"d":"[0.3095, 0.3572]",
"e":"[0.8085, 0.8582]"},
"image":"",
"Answer":"e"},

{"Question":"In the last revision class, 0.7 actively participated. What is the standard error if the population of students in attendance was 2500?",
"Option":{
"a":"0.038",
"b":"0.21",
"c":"0.029",
"d":"0.458",
"e":"No answer"},
"image":"",
"Answer":"e"},

{"Question":"If we use a ______ confidence percentage, then our margin of error will be _______.",
"Option":{
"a":"[small, large]",
"b":"[small, small]",
"c":"[large, small]",
"d":"[medium, large]",
"e":"[large, large]"},
"image":"",
"Answer":"e"},

{"Question":"Out 1500 students in Idia hostel, 1000 are allergic to Zikites so often avoid Zik hall route. Half of the remaining proportion wouldn't use Indy route as well. Obtain 95% confidence interval of the true population proportion of students who wouldn't use Indy route?",
"Option":{
"a":"[0.1478, 0.186]",
"b":"[0.1418, 0.1915]",
"c":"[0.1505, 0.1828]",
"d":"[0.8145, 0.8522]",
"e":"[0.8085, 0.8582]"},
"image":"",
"Answer":"e"},

{"Question":"A study finds that out of 2305 Awoites, 1383 Awoites are friends with Katangites. What is the margin of error, at 95% confidence interval?",
"Option":{
"a":"4%",
"b":"2%",
"c":"4.5%",
"d":"2.5%",
"e":"3%"},
"image":"",
"Answer":"e"},

{"Question":"What is the critical value if n = 20 and confidence interval is 99%?",
"Option":{
"a":"2.54q",
"b":"2.63",
"c":"2.86",
"d":"1.96",
"e":"2.58"},
"image":"",
"Answer":"e"},

{"Question":"Given that the MOE is ±4.5%. At 95% confidence interval and standard deviation of 2, what is the sample size?",
"Option":{"a":"0.7588",
"b":"76",
"c":"7588",
"d":"7588.34",
"e":"75.88"},
"image":"",
"Answer":"e"},

{"Question":"Out 1500 students in Idia hostel, 1000 are allergic to Zikites so often avoid Zik hall route. Half of the remaining proportion wouldn't use Indy route as well. Obtain 95% confidence interval of the true population proportion of students who wouldn't use Zik route?",
"Option":{"a":"[0.6353, 0.6981]",
"b":"[0.3019, 0.3647]",
"c":"[0.6428, 0.6905]",
"d":"[0.8145, 0.8522]",
"e":"[0.8085, 0.8582]"},
"image":"",
"Answer":"e"},

{"Question":"A study finds that 0.6 of every Awoite are friends with Zikites. If the MOE is 2%. How many Awoites are friends with Zikites?",
"Option":{"a":"2304.96",
"b":"2305",
"c":"23",
"d":"23.05",
"e":"46 "},
"image":"",
"Answer":"e"},

{"Question":"when the sample size is small and variance unknown, the test statistic to use is ___________",
"Option":{
"a":" Normal statistic",
"b":"t statistic",
"c":" Z statistic",
"d":" Unknown statistic"},
"image":"",
"Answer":""},

{"Question":" The 99 points that divide a line into 100 equal parts is called _____________",
"Option":{
"a":". percentile",  
"b":"decade",
"c":" deciles",
"d":" Quartiles"},
"image":"",
"Answer":""},

{"Question":" the fifth deciles is equivalent to__________",
"Option":{"a":" 60 percentiles",
"b":"lower quartiles",
"c":" Median",
"d":" Range"},
"image":"",
"Answer":""},

{"Question":"Which of the following is a measure of partition",
"Option":{"a":" Mean",
"b":"Median",
"c":" range",
"d":" deciles"},
"image":"",
"Answer":""},

{"Question":"Three points that divide a distribution into four equal part is known as the ",
"Option":{"a":"quartiles ",
"b":"quantiles",
"c":" Percentiles",
"d":" Percentages"},
"image":"",
"Answer":"a"},

{"Question":"Suppose 900 students were randomly selected for a national competition. If their average score was 2.7, and the standard deviation was 0.4. the value of standard error of the mean is  ",
"Option":{"a":" 0.0033",
"b":"0.1333",
"c":" 0.3333",
"d":" 0.0133"},
"image":"",
"Answer":"d"},

{"Question":"If the value of excess kurtosis is -2.40, then the data is said to be",
"Option":{"a":" sightly mesokurtic",
"b":"Slightly leptokurtic",
"c":" Sightly platykurtic",
"d":" None of the above"},
"image":"",
"Answer":""},

{"Question":"in a particular political campaign, a candidate has a poll taken at random from the voting population. The results given as y=59 out of n=112 voters favor the candidate. Find the 95percent confidence interval for P.",

"Option":{"a": "(0.435,0.619) ",
"b":"(0.435,0.690)",
"c":" (0.435,0.700)",
"d":"(0.435,0.500)"},
"image":"",
"Answer":""},

{"Question":"	Given the following set of data 25,10, 80, 12, 6, 90,100. the value of the inter-quartiles range is",  
"Option":{"a": "105 ",
"b":"100",
"c":" 95",
"d":" 90"},
"image":"",
"Answer":""},

{"Question":"	If $d <sub>i</sub><sup>2</sup> =20 and n=10. What is the coefficient of rank correlation",
"Option":{"a": "0.8788 ",
"b":"0.7887",
"c":" 0.8878",
"d":" 0.8 612"},
"image":"",
"Answer":""},

{"Question":"You are given the following set of observation for the independent variable x and the dependent variable y.  x=(-3,-1, 1, 3), y=(8,4,5,-1). The east squares linear regression equation is",

"Option":{"a": "y=-1.3+4x ",
"b":"y=4-1.3x ",
"c":" y=-1.3-0.897x",
"d":" y=-0.897-1.3x"},
"image":"",
"Answer":""},

{"Question":"Two men Aliyu and Bauta fell sick and were tested for HIV, In the course of labeling their blood sample, Mr Aliyu blood sample was mistakenly switched for Mr Bauta blood sample. At the end of the test, Mr Aliyu was tested positive. What error has the doctor committed",

"Option":{"a": "Type II ",
"b":"Type I",
"c":" Absolute error",
"d":" No error"},
"image":"",
"Answer":""},

{"Question":"The error committed when a false nu hypothesis is assumed to be true is ______",

"Option":{"a": "Type II ",
"b":"Type I",
"c":" Absolute error",
"d":" Type Nu error"},
"image":"",
"Answer":""},

{"Question":"	Which of the following is TRUE",

"Option":{
"a": "increase in sample size will increase the beta ( i.e P(Accept H<sub>0: H<Sub>0</sub> is false ) value",
"b":"increase in sample size will reduce the beta ( i.e P(Accept H<sub>0</sub>: H<sub>0</sub> is false ) value",
"c":" increase in sample size will increase the alpha ( i.e P(Accept H<sub>0</sub>: H<sub>0</sub> is false ) value",
"d":" increase in sample size will reduce the alpha ( i.e P(Reject H<sub>0</sub>: H<sub>0</sub> is true ) value"},
"image":"",
"Answer":""},

{"Question":"	The value of two variable moves in the same direction, __",

"Option":{
"a": "The correlation is said to be non-linear ",
"b":"The correlation is said to be linear",
"c":" the correlation is said to be negative",
"d":" the correlation is said to be positive"},
"image":"",
"Answer":""},

{"Question":"	The domain of statistics covered data collection, ________,____ analysis and report writing  ",
"Option":{"a": "description, management ",
"b":"Management, processing ",
"c":" processing, description",
"d":" usage, management."},
"image":"",
"Answer":""},

{"Question":"	If the value of two variable moves in the opposite direction, ______",

"Option":{"a": "The correlation is said to be non-linear ",
"b":"The correlation is said to be linear",
"c":" the correlation is said to be negative",
"d":" the correlation is said to be positive"},
"image":"",
"Answer":""},

{"Question":"Ethnicity is an example of a variable measured on _______scale",   
   "Option":{"a": "A Nominal  ",
   "b":"An  interval",
   "c":" A ratio",
   "d":" an ordinal"},
   "image":"",
   "Answer":""},

{"Question":"The independent variable is used to explain the dependent variable in ____",
"Option":{"a": "linear regression analysis ",
"b":"multiple regression analysis",
"c":" Non-linear regression analysis",
"d":" None of the above"},
"image":"",
"Answer":""},

{"Question":"----------is an example of a discrete variable  ","Option":{"a": "weight ",
"b":"color",
"c":" family size",
"d":" gender"},
"image":"",
"Answer":""},

{"Question":"Below is the inventory of beverages in a store , which beverage is the highest in quantity in the store.  Coca-cola, Sprite, Fanta, Pepsi, Fanta, Sprite, fanta, Pepsi, Coca-cola, Fanta, Coca-cola, Pepsi, Pepsi, Coca-cola, Fanta, Pepsi, Sprite.",
"Option":{"a": "Pepsi ",
"b":"Fanta",
"c":" Coca-cola",
"d":" Sprite"},
"image":"",
"Answer":""},

{"Question":"__should be indicated at the bottom of a table  ",
"Option":{"a": "Relevance ",
"b":"Repeatability",
"c":" Objectivity",
"d":" integrity"},
"image":"",
"Answer":""},

{"Question":"Which of the following statements is true about the regression line",

"Option":{"a": "A regression line is also known as the line of average relationship",

"b":" A regression line is also known as the estimating equation",
"c":"  A regression line is also known as the prediction equation",
"d":" A of the above"},
"image":"",
"Answer":""},

{"Question":"what is frequency of object",

"Option":{"a": "frequency gives the number of times that an entry occurs",

"b":"frequency gives the number of times that an entry occurs per unit time",
"c":" frequency gives the percentage of times that an entry occurs",
"d":" frequency gives the fraction of times that an entry occurs"},
"image":"",
"Answer":""},

{"Question":"___ is not a type of survey ",
"Option":{"a": "Social survey ",
"b":"Market research",
"c":" opinion polls",
"d":" talk show"},
"image":"",
"Answer":""},

{"Question":"statistical abstract is an example of data from ____sources",

"Option":{"a": "official ",
"b":"published",
"c":" unofficial",
"d":" unpublished"},
"image":"",
"Answer":""},

{"Question":"consider the table below, compute the cumulative frequency of the distribution <br> <table border=\"2\"><tr><th>Score</th> <td>3</td><td>5</td><td>6</td><td>8</td><td>9</td></tr><tr><th>Frequency </th> <td>3</td><td>2</td><td>1</td><td>3</td><td>2</td></tr></table>",


"Option":{"a": "11 ",
"b":"10",
"c":" 13",
"d":"9"},
"image":"",
"Answer":""},

{"Question":"Using the data below compute range for the score<br> <table border=\"2\"><tr><th>Score</th> <td>3</td><td>5</td><td>6</td><td>8</td><td>9</td></tr><tr><th>Frequency </th> <td>3</td><td>2</td><td>1</td><td>3</td><td>2</td></tr></table>",

"Option":{"a": "9 ",
"b":"8",
"c":" 6",
"d":" 10"},
"image":"",
"Answer":""},

{"Question":"Class mark is the ___of a class interval ",
"Option":{"a": "range ",
"b":"endpoint",
"c":" midpoint",
"d":" boundary"},
"image":"",
"Answer":""},

{"Question":"Given the hypothesis below at 5percent level  of significance.<br> H <sub>0</sub> : There is GOD<br> H<sub>a</sub>  :there is No GOD<br> what conclusion can you draw from this hypothesis if the Z calculated is 1.99",

"Option":{"a": "We reject the null hypothesis, hence there is no adequate evidence that GOD exist.",
"b":"We reject the null hypothesis, hence there is adequate evidence that GOD exist.",
"c":" We reject the null hypothesis, hence there is little or no evidence to support the  H<sub>0</sub> ",
"d":" We accept the null hypothesis, hence there is no sufficient evidence against the null"},
"image":"",
"Answer":""},
{"Question":"	Which of the following does not pertain to descriptive statistics?",
"Option":{"a": "Graphical presentation of quantitative data ",
"b":" summarizing quantitative data ",
"c":" making generalization about a population from sample data ",
"d":"collecting quantitative data"},
"image":"",
"Answer":"c"},

{"Question":"	What are the three measures that can be used to describe a set of quantitative data?",
"Option":{"a": "skewness, median, mode ",
"b":" location, mean, mode ",
"c":" location, skewness, shape ",
"d":" mean, mode, data"},
"image":"",
"Answer":"d"},

{"Question":"	What is the relationship between arithmetic, geometric and assumed means?",
"Option":{"a":"A.M≤H.M≤G.M ",
"b":"H.M≤G.M≤A.M ",
"c":" H.M≥G.M≥H.M ",
"d":" none of the above"},
"image":"",
"Answer":""},

{"Question":"	If the variance of a distribution is 49, what is its standard deviation?",
"Option":{"a":  "8 ",
"b":"9 ",
"c":" 7 ",
"d":" none of the above"},
"image":"",
"Answer":"c"},

{"Question":"	The most occurring value in a distribution is ...........",
"Option":{"a":"mean ",
"b":" mode ",
"c":" median ",
"d":" range"},
"image":"",
"Answer":"b"},


{"Question":"The most occurring value in a distribution is ........... ",
"Option":{"a":" mean ",
"b":" mode ",
"c":" median ",
"d":" range"},
"image":"",
"Answer":""},

{"Question":"In order to compute the Pearson’s measured of skewness of any distribution, we need ................. ",
"Option":{"a":" mean,median, standard deviation ",
"b":" median and standard deviation ",
"c":"mean and median ",
"d":" mean and standard deviation"},
"image":"",
"Answer":""},

{"Question":"The section of statistics that involves the collection, organization and presentation of data relating to some population or example is ............. ",
"Option":{"a":" classical statistics ",
"b":" inductive statistics ",
"c":" descriptive statistics ",
"d":"inferential statistics"},
"image":"",
"Answer":""},


{"Question":"Data such as gender, eye color, ethnicity etc. are classified as ",
"Option":{"a":" ordinal ",
"b":" nominal ",
"c":" ratio ",
"d":" none of the above"},
"image":"",
"Answer":""},

{"Question":"In a set of discrete values of observation, 50% of the values are greater than 25, then Q 2 IS ....... ",
"Option":{"a":"100 ",
"b":"25 ",
"c":"75 ",
"d":"0.25"},
"image":"",
"Answer":""},

{"Question":"	A statement made stating that students in a class are between ages 25 and 50 years gave us what information. ",
"Option":{"a":"range ",
"b":"mode ",
"c":"mean ",
"d":"median"},
"image":"",
"Answer":""},

{"Question":"	What type of distribution is described by the following information: Mean=56, Median=57, Mode=58",

"Option":{"a":" Symmetrical ",
"b":" Bimodal ",
"c":" Positively skewed ",
"d":" Negatively skewed"},
"image":"",
"Answer":""},

{"Question":"	The data 3,5,7,3,5 can be described as ........... ",
"Option":{"a":" bimodal ",
"b":" bi-variate ",
"c":"all of the above ",
"d":" none of the above"},
"image":"",
"Answer":""},

{"Question":"	An unknown population value is referred to as ......... ",
"Option":{"a":" parameter ",
"b":" statistic ",
"c":" variable ",
"d":" X"},
"image":"",
"Answer":""},

{"Question":"	Greek letters are used to represent ........... ",
"Option":{"a":" sample values ",
"b":" population values ",
"c":" all of the above ",
"d":" none of the above"},
"image":"",
"Answer":""},

{"Question":"	Which of these is not a type of estimation? ",
"Option":{"a":" point estimation ",
"b":" sample estimation ",
"c":" interval estimation ",
"d":" none of the above"},
"image":"",
"Answer":""},

{"Question":"	The more reliable types of estimates  Is .......................…",

"Option":{"a":" point estimation ",
"b":" sample estimation ",
"c":" interval estimation ",
"d":" none of the above"},
"image":"",
"Answer":""},

{"Question":"	The formula for calculating confidence interval is ........................ ",
"Option":{"a":" Point estimate + Margin of error ",
"b":"Point estimate - Margin of error ",
"c":" Point estimate ± Margin of error ",
"d":" none of the above."},
"image":"",
"Answer":""},

{"Question":"	Z C × Standard error is the formula for calculating ............. ",
"Option":{"a":" Critical value ",
"b":" Hypothesis making ",
"c":" Margin of error ",
"d":" ) none of the above."},
"image":"",
"Answer":""},

{"Question":"	The standard error for population mean is .................. ",
"Option":{"a":"σ/ √n ",
"b":"σ ",
"c":" n ",
"d":" Z C × MOE"},
"image":"",
"Answer":""},

{"Question":"	The critical value in a 99% confidence interval is .................…",
 "Option":{"a":"1.96",
 "b":"2.54",
 "c":"2.576",
 "d":"1.645"},
 "image":"",
"Answer":""},


{"Question":"Three properties of a sample distribution of a sample mean are .............. ",
"Option":{"a":" center, mean, mode ",
"b":" median,spread, shape ",
"c":" center, spread, shape ",
"d":"mean, mode, median"},
"image":"",
"Answer":""},

{"Question":"	The value number of success sample size is known as: ",
"Option":{"a":" sample mean ",
"b":"sample distribution ",
"c":"sample properties ",
"d":"none of the above"},
"image":"",
"Answer":""},

{"Question":"An initial statement such as ‘The mean is 12’ can be known as",
"Option":{"a":"null hypothesis ",
"b":"test statistic ",
"c":"type-1 error ",
"d":" it does not have any meaning"},
"image":"",
"Answer":""},

{"Question":"	The processes for hypothesis testing arranged in order are<br>"+
"(i)State H0 and Ha<br>"+
"(ii)Establish critical or rejection region<br>"+
"(iii)State level of significance<br>"+
"(iv)Reach a conclusion<br>"+
"(v)Calculate suitable test statistic",

"Option":{"a":" i,ii,iii,iv,v ",
"b":"i,iv,iii,ii,v ",
"c":"i,ii,iii,v,v ",
"d":"i,iii,ii,v,iv"},
"image":"",
"Answer":""},

{"Question":"The power of a statistical test is given by:",
"Option":{"a":"1-α ",
"b":"1-β ",
"c":"α ",
"d":"β"},
"image":"",
"Answer":""},

{"Question":"	If the null hypothesis is ‘Musa is 10 years old’. The alternate hypothesis will be given as .....................................…",
"Option":{"a":"‘Musa is not 10 years old’",
"b":"‘Musa is greater than 10 years old’ ",
"c":"‘Musa is below 10 years old’",
"d":"‘Musa is not more 10 years old’"},
"image":"",
"Answer":""},


{"Question":".	A frequency curve that is flat-topped than the normal curve is referred to as",
 "Option":{"a":" Kurtosis",
"b":" Platykurtic",
"c":" Mesokurtic",
"d":" Moment"},
"image":"",
"Answer":""},

{"Question":"Find the first four moments about the mean for the set of numbers 2,4,6,8",
"Option":{"a":"	0, 5, 0, 41 ",
"b":" 0, 0, 5, 41",
"c":" 0,41,5,0",
"d":" 0,4,0,5"},
"image":"",
"Answer":""},

{"Question":"If an observation in the data set is negative then its geometric mean is ",
"Option":{"a":"	Negative ",
"b":" Positive ",
"c":" Zero ",
"d":" Indeterminate "},
"image":"",
"Answer":""},

{"Question":"Examine the following data set<br> 15, 16, 17, 17, 18, 9, 18 <br> The data set can be characterized as",
 "Option":{"a":" Unimodal",
"b":" Bimodal",
"c":" Multimodal",
"d":" All of the above."},
"image":"",
"Answer":""},

	
{"Question":"if the population standard deviation is not known and n is less  30,use the_____",
"Option":{"a":"	F distribution",
"b":"Z distribution",
"c":"Student t distribution",
"d":"Chi square distribution"},
"image":"",
"Answer":""},

{"Question":"The number that divides the critical region from the noncritical region is the_________________",
"Option":{"a":" Confidence coefficient",
"b":"Confidence interval",
"c":"Critical value",
"d":"Confidence limits"},
"image":"",
"Answer":""},

{"Question":"The expected value of the sampling distribution of the sample mean is equal to ",
"Option":{"a":"	Sample variance",
"b":"Sample mean",
"c":"Population variance",
"d":"Population mean"},
"image":"",
"Answer":""},

{"Question":"If we change the confidence level from 98 to 95 percent when constructing a confidence interval for the population mean, we can expect the size of the interval to_______",
"Option":{"a":"	Increase",
"b":"Decrease",
"c":"Remain the same",
"d":"Be undefined"},
"image":"",
"Answer":""},

{"Question":"Find the first four moment about the mean for the set of numbers 2, 4, 6,14 and 8",
"Option":{"a":"	0,14,70,80",
"b":"0,18,50,690",
"c":"0,16.96,48.38,656.44",
"d":"0,20.65,52.12,98.36"},
"image":"",
"Answer":""},

{"Question":"	The second moment about the mean is also known as",
"Option":{"a":"	Variance",
"b":"Mean",
"c":"Skewness",
"d":"zero"},
"image":"",
"Answer":""},

{"Question":"What is the first moment about the origin also known as_________________",
"Option":{"a":"	Variance",
"b":"Undefined",
"c":"Zero",
"d":"mean"},
"image":"",
"Answer":""},

{"Question":"For a negatively skewed data , which one of the following is true",
"Option":{"a":"	mode < mean < median",
"b":"mode>median>mean",
"c":"mode < median < mean",
"d":"mean < median > mode"},
"image":"",
"Answer":""},


{"Question":"For a positively skewed data , which one of the following is",
"Option":{"a":" median > mode > mean",
"b":"mean < median < mode",
"c":"mean > median > mode",
"d":"mode < mean < median"},
"image":"",
"Answer":""},


{"Question":"	The distribution shape of quantitative data can be described as the",
"Option":{"a":"	logical order that are numeric",
"b":"logical order that are non-numeric",
"c":"logical order that are qualitative",
"d":"logical order",
"e":"none of the above"},
"image":"",
"Answer":""},

{"Question":"	The shape of an asymmetric distribution is",
"Option":{"a":"	bell shape",
"b":"cup shape",
"c":"has no shape",
"d":"skewed",
"e":"none of the above"},
"image":"",
"Answer":""},

{"Question":"	If skewness is positive, the data are _____ skewed or skewed _____.",
"Option":{"a":"	negatively, right.",
"b":"positively, right.",
"c":"positively, left.",
"d":"negatively, left.",
"e":"uni-modal, central"},
"image":"",
"Answer":""},

{"Question":"	Which of the following is a key feature of a asymmetric distribution? Indicate all that apply.",
"Option":{"a":"	uni-modal",
"b":"	bi-modal",
"c":"	heavy tailed",
"d":"	uneven distribution",
"e":"all of the above"},
"image":"",
"Answer":""},
	
{"Question":"	Which of the following is a key feature of a symmetric distribution?",
"Option":{"a":"	uni-modal",
"b":"	bi-modal",
"c":"	heavy tailed",
"d":"	plykurtic",
"e":"uneven distribution"},
"image":"",
"Answer":""},


{"Question":"	In a symmetrical distribution the two sides of the distribution are equally distributed",
"Option":{"a":"	symmetric",
"b":"	asymmetric",
"c":"	skewed",
"d":"	partitioned"},
"image":"",
"Answer":""},

{"Question":"	A distribution is said to be negatively skewed when the tail on the ___ side of the histogram is _____ than the _____ side.",
"Option":{"a":"	right, longer, left",
"b":"	left, longer, right",
"c":"	right, shorter, left",
"d":"	left, shorter, right",
"e":"centre, longer, right and left"},
"image":"",
"Answer":""},

{"Question":"	A distribution is said to be positively skewed when the tail on the ___ side of the histogram is _____ than the _____ side.",
"Option":{"a":"	right, longer, left",
"b":"	left, longer, right",
"c":"	right, shorter, left",
"d":"	left, shorter, right",
"e":"centre, longer, right and left"},
"image":"",
"Answer":""},

{"Question":"	The outliers in shape of distribution of a sample have more effect on the ____ is than they do on the ____.",
"Option":{"a":"	mean, median",
"b":"	skewness, kurtosis.",
"c":"	symmetric, asymmetric",
"d":"	mean, mode",
"e":"kurtosis, skewness."},
"image":"",
"Answer":""},
	
{"Question":"	A mesokurtic shaped distribution is _________?",
"Option":{"a":"	asymmetric",
"b":"	symmetric",
"c":"	beta distributed",
"d":"	balanced",
"e":"spread"},
"image":"",
"Answer":""},


{"Question":"	What is the critical value if n = 100 and confidence interval is 99%?",
"Option":{"a":"	1.96",
"b":"	2.32",
"c":"	2.63",
"d":"	1.68",
"e":"2.58"},
"image":"",
"Answer":""},


{"Question":"	Out 1500 students in Idia hostel, 1000 are allergic to Zikites so often avoid Zik hall route. Half of the remaining proportion wouldn't use Indy route as well. Obtain 95% confidence interval of the true population proportion of students who would use Zik route?",
"Option":{"a":"	[0.6353, 0.6981]",
"b":"	[0.3019, 0.3647]",
"c":"	[0.8145, 0.8522]",
"d":"	[0.3095, 0.3572]",
"e":"[0.8085, 0.8582]"},
"image":"",
"Answer":""},


{"Question":"	 In the last revision class, 0.7 actively participated What is the standard error if the population of students in attendance was 2500?",
"Option":{"a":"	0.038",
"b":"	0.21",
"c":"	0.029",
"d":"	0.458",
"e":"No answer"},
"image":"",
"Answer":""},

{"Question":"	 If we use a ______ confidence percentage, then our margin of error will be _______.",
"Option":{"a":"	[small, large]",
"b":"	[small, small]",
"c":"	[large, small]",
"d":"	[medium, large]",
"e":"[large, large]"},
"image":"",
"Answer":""},


{"Question":"	Out 1500 students in Idia hostel, 1000 are allergic to Zikites so often avoid Zik hall route. Half of the remaining proportion wouldn't use Indy route as well. Obtain 95% confidence interval of the true population proportion of students who wouldn't use Indy route?",
"Option":{"a":"	[0.1478, 0.186]",
"b":"	[0.1418, 0.1915]",
"c":"	[0.1505, 0.1828]",
"d":"	[0.8145, 0.8522]",
"e":"[0.8085, 0.8582]"},
"image":"",
"Answer":"e"},

{"Question":"	What is the margin of error, at 95% confidence interval?",
"Option":{"a":"	4%",
"b":"2%",
"c":"4.5%",
"d":"2.5%",
"e":"3%"},
"image":"",
"Answer":"b"},
	
{"Question":"	What is the critical value if n = 20 and confidence interval is 99%?",
"Option":{"a":"	2.54q",
"b":"2.63",
"c":"2.86",
"d":"1.96",
"e":"2.58"},
"image":"",
"Answer":"a"},


{"Question":"	Given that the MOE is ±4.5%. At 95% confidence interval and standard deviation of 2, what is the sample size?",
"Option":{"a":"	0.7588",
"b":"76",
"c":"7588",
"d":"7588.34",
"e":"75.88"},
"image":"",
"Answer":"c"},

{"Question":"	Out 1500 students in Idia hostel, 1000 are allergic to Zikites so often avoid Zik hall route. Half\of the remaining proportion wouldn't use Indy route as well. Obtain 95% confidence interval of the true population proportion of students who wouldn't use Zik route?",
"Option":{"a":"	[0.6353, 0.6981]",
"b":"[0.3019, 0.3647]",
"c":"[0.6428, 0.6905]",
"d":"[0.8145, 0.8522]",
"e":"[0.8085, 0.8582]"},
"image":"",
"Answer":"c"},


{"Question":"	A study finds that 0.6 of every Awoite are friends with Zikites. If the MOE is 2%. How many Awoites are friends with Zikites?",
"Option":{"a":"	2304.96",
"b":"2305",
"c":"23",
"d":"23.05",
"e":"46"},
"image":"",
"Answer":"b"},

{"Question":"	Given the following frequencies; 2, 3, 5, 16, 3, 5. What is the cumulative frequency of the fourth class?",
"Option":{"a":"	34",
"b":"16",
"c":"10",
"d":"26",
"e":"29"},
"image":"",
"Answer":"d"},

{"Question":"If a population parameter is estimated by a single number, the resulting estimate is known as a",
"Option":{
"a":"just estimate",
"b":"statistics",
"c":"point estimate",
"d":"interval estimate",
"e":"parameter"},
"Answer":""},

{"Question":"______________ is defined interval within which an hypothetical value must lie before it could be accepted as a member of a population?",
"Option":{
"a":"Confident gain	",
"b":"Confident point",
"c":"Confidence interval",
"d":"Confidence coefficient",
"e":"Confidence level"},
"Answer":""},

{"Question":"For 2-tailed 95% confidence level, each rejection region covers _______ of the standard normal distribution curve.",
"Option":{
"a":"5%",
"b":"2.5%",
"c":"1- α",
"d":"α",
"e":"1 − β"},
"Answer":""},

{"Question":"_______________ are the boundaries of the acceptance region of a standard distribution curve.",
"Option":{
"a":"1 − β",
"b":"±Zβ/2",
"c":"±Zα/2",
"d":"1 ± Zβ/2",
"e":"1 ± Zα/2"},
"Answer":""},

{"Question":"The end points of a defined confidence interval is known as ______",
"Option":{
"a":"Confidence limits",
"b":"Confidence intervals",
"c":"Confidence coefficients",
"d":"Confident of significance",
"e":"Confidence points"},
"Answer":""},

{"Question":"The degree of freedom is _______",
"Option":{
"a":"1 - α",
"b":"1 − β",
"c":"n - 1",
"d":"β - 1",
"e":"α - 1"},
"Answer":""},

{"Question":"____________ is a region of a standard distribution curve within which the standard form of an hypothetical value must lie if it is to be accepted as a member of the population within the region.",
"Option":{
"a":"1-α",
"b":"1 − β",
"c":"β",
"d":"2(1 − β)",
"e":"α"},
"Answer":""},

{"Question":"____________ is the area of the standard distribution curve covered by the rejection region.",
"Option":{
"a":"1-α",
"b":"1 − β",
"c":"β",
"d":"2(1 − β)",
"e":"α"},
"Answer":""},

{"Question":"When is sample size assumed large (in the context of this course)?",
"Option":{
"a":"n < 30",
"b":"n > 30",
"c":"n >= 30",
"d":"n > 50",
"e":"n >= 50"},
"Answer":""},

{"Question":"If sample size is small, which of the following statistics is appropriate?",
"Option":{
"a":"F",
"b":"Z",
"c":"t",
"d":"Chi-square",
"e":""},
"Answer":""}

]	
}
